from __future__ import annotations

from pathlib import Path
from tempfile import gettempdir

from reportlab.lib import colors
from reportlab.lib.pagesizes import letter
from reportlab.lib.styles import getSampleStyleSheet
from reportlab.platypus import Paragraph, SimpleDocTemplate, Spacer, Table, TableStyle
from sqlalchemy.orm import Session

from app.agent.anthropic_agent import get_recommendations_tool, get_risk_assessment_tool
from app.db import models


# Generates a styled clinician-facing PDF from a stored Glyco report and the
# latest live model state.
def generate_pdf_report(db: Session, report_id: int) -> Path:
    """Produce a styled PDF for a report and return its filesystem path."""
    report = db.get(models.Report, report_id)
    if not report:
        raise ValueError("Report not found")
    user = db.get(models.User, report.user_id)
    risk = db.query(models.RiskAssessment).filter(models.RiskAssessment.user_id == report.user_id).order_by(models.RiskAssessment.created_at.desc()).first()
    monitoring = db.query(models.MonitoringAssessment).filter(models.MonitoringAssessment.user_id == report.user_id).order_by(models.MonitoringAssessment.created_at.desc()).first()
    logs = db.query(models.HealthLog).filter(models.HealthLog.user_id == report.user_id).order_by(models.HealthLog.log_date.desc()).limit(7).all()
    bayesian = get_risk_assessment_tool(db, report.user_id)["bayesian"]
    recommendations = get_recommendations_tool(db, report.user_id, limit=3)
    output_dir = Path(gettempdir()) / "glyco_reports"
    output_dir.mkdir(parents=True, exist_ok=True)
    path = output_dir / f"glyco_report_{report_id}.pdf"
    styles = getSampleStyleSheet()
    doc = SimpleDocTemplate(str(path), pagesize=letter, rightMargin=42, leftMargin=42, topMargin=42, bottomMargin=36)
    story = [
        Paragraph("Glyco", styles["Title"]),
        Paragraph("Clinical editorial support report", styles["Normal"]),
        Spacer(1, 14),
        Paragraph(f"Patient: {user.full_name if user else 'Unknown'}", styles["Heading2"]),
        Paragraph(f"Date: {report.created_at.date().isoformat()}", styles["Normal"]),
        Spacer(1, 12),
        Paragraph("Current Risk", styles["Heading2"]),
        Paragraph(
            f"{risk.risk_level if risk else 'Unknown'} risk. Bayesian posterior mean "
            f"{bayesian['posterior_mean']:.2f} with 95% credible interval "
            f"{bayesian['credible_interval']['low']:.2f}-{bayesian['credible_interval']['high']:.2f}.",
            styles["Normal"],
        ),
        Spacer(1, 10),
        Paragraph("Monitoring Trend", styles["Heading2"]),
        Paragraph(f"{monitoring.trend_label if monitoring else 'No monitoring trend available'}.", styles["Normal"]),
        Spacer(1, 10),
        Paragraph("Last 7 Glucose Readings", styles["Heading2"]),
    ]
    table_rows = [["Date", "Fasting", "Post-meal", "Activity"]]
    for log in reversed(logs):
        table_rows.append([
            log.log_date.isoformat(),
            f"{log.fasting_glucose:g}",
            f"{log.post_meal_glucose:g}" if log.post_meal_glucose is not None else "-",
            str(log.activity_minutes or 0),
        ])
    table = Table(table_rows, hAlign="LEFT")
    table.setStyle(TableStyle([
        ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#2f5d50")),
        ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),
        ("GRID", (0, 0), (-1, -1), 0.4, colors.HexColor("#ccd7d2")),
        ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
        ("PADDING", (0, 0), (-1, -1), 6),
    ]))
    story.extend([table, Spacer(1, 12), Paragraph("Top Recommendations", styles["Heading2"])])
    for item in recommendations:
        story.append(Paragraph(f"<b>{item['title']}</b>: {item['body']}", styles["Normal"]))
    story.extend([Spacer(1, 18), Paragraph("Not a diagnostic tool. Generated by Glyco.", styles["Italic"])])
    doc.build(story)
    return path
